### ISSUE TITLE
what is ideal size of GPU, Batch_size for training ? I'm getting a CUDA out of memory error for genia dataset.

### ISSUE THREAD

**Issue by yaswanth-iitkgp** [LouChao98/nner_as_parsing#2]
`RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 44.40 GiB total capacity; 26.45 GiB already allocated; 10.81 MiB free; 27.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I'm using the similar config file as ACE dataset. Please tell me what extra tweaks maybe needed.

**Comment by LouChao98** [comment]
There is a mistake of not including the config file for GENIA. I have added it. 

You need to set a `max_len` for training because our model requires O(n^3) memory for a length-n sentence. You can find it at here 
https://github.com/LouChao98/nner_as_parsing/blob/d3fe3462ab4e975fbc9e391b336d341c9649af25/conf/model/genia.yaml#L53-L54

**Comment by yaswanth-iitkgp** [comment]
I still get the following error : 

```
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'runner' is not in struct
    full_key: runner
    object_type=dict
```

**Comment by LouChao98** [comment]
I have updated the config file. There is a missing line at the top..

**Comment by yaswanth-iitkgp** [comment]
still I get the same error

**Comment by yaswanth-iitkgp** [comment]
is the config file for genia corrected now ??

**Comment by yaswanth-iitkgp** [comment]
Can you please check the config file you gave ? Because it is still giving
errors

**Comment by LouChao98** [comment]
Sorry for the late reply. I have updated config, which is tested using the code in this repo.

**Comment by yaswanth-iitkgp** [comment]
thanks , and how to get this file ? 
`data/bio_nlp_vec/PubMed-shuffle-win-30.txt`

**Comment by LouChao98** [comment]
https://github.com/cambridgeltl/BioNLP-2016

**Comment by yaswanth-iitkgp** [comment]
Yes I got it too and requested them for the word vectors access (drive link was given without access). But is there any other way to get it or ?

**Comment by LouChao98** [comment]
I create a share link, https://drive.google.com/file/d/0BzMCqpcgEJgiUWs0ZnU0NlFTam8/view?usp=sharing&resourcekey=0-hKMdnLPkaFZZYNiIMeyoww Can you use it?
