### ISSUE TITLE
What should be the choice of hyperparameters (for config file) for another dataset with 86 types of entities ? When I use the same config file as genia I get cuda out of memory error (using a 45gb GPU)

### ISSUE THREAD

**Issue by yaswanth-iitkgp** [LouChao98/nner_as_parsing#4]
My dataset has about 86 types of labels and it is quite small and has only 11k lines and their Span tags. Can you tell how to choose hyperparameters used in config file ?? @LouChao98

**Comment by LouChao98** [comment]
In our NNE experiments, we have 114 labels and can run this code on a 24GB GPU. So I don't think the number of labels matters. The most significant factor is the sentence length. In the config file, you can limit `datamodule.max_len.train` to a reasonable value (the current value 120 should be fine). 

I recommend to use a small batch size first. i.e., set `dataloader.default.batch_size` to 16. 

A 45GB GPU should be very abundant. I am not sure about the real reason of OOM.

**Comment by yaswanth-iitkgp** [comment]
I tried using batch size = 4 and max_len = 30 even but still I get OOM 
`
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 GiB (GPU 0; 44.40 GiB total capacity; 29.88 GiB already allocated; 13.29 GiB free; 29.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

Should I try changing anything else like label_mlp_hidden or something?

**Comment by LouChao98** [comment]
At which statement you get the OOM? Could you also print the length of the input causing OOM?

**Comment by yaswanth-iitkgp** [comment]
Also if I change label_mlp_hidden to 192 then it trains the model for some time and it doesn't go ahead 

`[1] train:  88% 2461/2793 [13:47<01:51,  2.98it/s, loss=4.51, bs=4, mlen=8, struct=1.02, lab[1] train:  88% 2462/2793 [13:47<01:51,  2.98it/s, loss=4.51, bs=4, mlen=8, struct=1.02, lab[1] train:  88% 2462/2793 [13:47<01:51,  2.98it/s, loss=4.37, bs=4, mlen=14, struct=1.87, label=1.84, exp_entropy=-.306]> /home/model4/nner_as_parsing/src/task_specific/ner_onestage2_gonly.py(241)forward()
-> vp.span_list = span_list
(Pdb) `

**Comment by yaswanth-iitkgp** [comment]
> At which statement you get the OOM? Could you also print the length of the input causing OOM?

it doesn't start the training even, so OOM occurs in the beginning itself. should still try to print and tell you.

**Comment by LouChao98** [comment]
> Also if I change label_mlp_hidden to 192 then it trains the model for some time and it doesn't go ahead
> 
> `[1] train: 88% 2461/2793 [13:47<01:51, 2.98it/s, loss=4.51, bs=4, mlen=8, struct=1.02, lab[1] train: 88% 2462/2793 [13:47<01:51, 2.98it/s, loss=4.51, bs=4, mlen=8, struct=1.02, lab[1] train: 88% 2462/2793 [13:47<01:51, 2.98it/s, loss=4.37, bs=4, mlen=14, struct=1.87, label=1.84, exp_entropy=-.306]> /home/model4/nner_as_parsing/src/task_specific/ner_onestage2_gonly.py(241)forward() -> vp.span_list = span_list (Pdb) `

Does the OOM always occur at line 241? How many items the `span_list` has?

**Comment by yaswanth-iitkgp** [comment]
no not in line 241 always, anyways now it is still training and didn't stop. what is span_list ? in config span_list = true

**Comment by LouChao98** [comment]
Nevermind. `span_list` is used at line 241. If always OOM here, I would like to check the size of span_list.

**Comment by yaswanth-iitkgp** [comment]
I was able to successfully train the model using a `batch_size of 32, max_len=80 and label_mlp_hidden=192` (instead of 384) this config takes about 42 gb GPU and if use a smaller `batch_size like 8 or 4 and max_len=60 and label_mlp_hidden=192` then it takes about 21.5 gb GPU

Thanks a lot.
