### ISSUE TITLE
如何获取/data/bio_nlp_vec/PubMed-shuffle-win-30.txt文件

### ISSUE THREAD

**Issue by thy1999** [LouChao98/nner_as_parsing#5]
您好，目前我正在genia数据集上复现您的NNER模型，但是在复现过程中遇到了一些问题，我想问一下配置文件中涉及到的/data/bio_nlp_vec/PubMed-shuffle-win-30.txt文件该如何获得，目前我只能在网上找到PubMed-shuffle-win-30.bin和PubMed-shuffle-win-2.bin文件，但是好像不能用在该模型中，不知道您是否可以提供一下PubMed-shuffle-win-30.txt词向量文件呢？

**Comment by thy1999** [comment]
> 您好，目前我正在genia数据集上复现您的NNER模型，但是在复现过程中遇到了一些问题，我想问一下配置文件中涉及到的/data/bio_nlp_vec/PubMed-shuffle-win-30.txt文件该如何获得，目前我只能在网上找到PubMed-shuffle-win-30.bin和PubMed-shuffle-win-2.bin文件，但是好像不能用在该模型中，不知道您是否可以提供一下PubMed-shuffle-win-30.txt词向量文件呢？

**Comment by LouChao98** [comment]
请参考 https://github.com/LouChao98/nner_as_parsing/issues/3#issuecomment-1482534356

**Comment by santiagoTOP** [comment]
@thy1999 请问Med-shuffle-win-30.bin和PubMed-shuffle-win-2.bin可以发我一份吗？我在网上没有找到相关信息，谢谢了！

**Comment by LouChao98** [comment]
https://github.com/cambridgeltl/BioNLP-2016
